---
title: "Data Sources And Literature Review"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Sources And Literature Review}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# General Overview

The tool built in this project is built based on the Excel tool created by the Iowa State University Food and Farm Enterprise development FFED. The documentation and calculations done in those Excel sheets were understood, recreated, and improvised in this package.

# Data Utilized

## [ACS Data](https://www.census.gov/programs-surveys/acs/data.html)

The demographic data for this project is taken from the five-year American Community Survey(ACS) 2021. The plots in the dashboard showing the language, race, employment rate, and median income use the 2021 five-year ACS data. The population used in the function, `Avg_Capita_Grocery_Spending()`, of this project, takes the ACS 1-year data as of 01/01/2022.

## [Decennial Data](https://www.census.gov/programs-surveys/decennial-census/data.html)

The population data for the visualizations in this project is taken from the US Census Bureau's 2020 Decennial data. This data is used for the population because it is the full count and not a sample, unlike the ACS data.

## [IBIS Data](https://help.ibisworld.com/s/article/methodology-and-sources)

This project uses the 2022 total grocery sales data from IBIS World in the function `Avg_Capita_Grocery_Spending()`. The total grocery sales is the total money spent on groceries in the US in 2022.

## [BLS Data](https://data.bls.gov/timeseries/CUUR0000SA0)

The US Bureau of labor statistics(BLS) Consumer Price Index(CPI) data was used in this project for calculating the inflation from the base year. This value is planned to be updated every month on the website, but for this package, it is updated every six months since that does change too much every month.

## [BEA Data](https://tinyurl.com/2wvca7vy)

Bureau of Economic Analysis's data on regional price parities was used to adjust the spending according to the regional price levels after adjusting for the overall inflation using the CPI. This data is updated yearly.

## [SalesGenie](https://www.dataaxlegenie.com/lp/genie/?bas_phone=877.846.6920&mediacode=SGNGAWS05038&sfcid=7010d000001K16nAAC&campaignid=1370030323&adgroupid=58327803567&keyword=salesgenie&matchtype=p&network=g&device=c&extensionid=&gad=1&gclid=EAIaIQobChMI7viYnomMgAMVOvfjBx3_xgnMEAAYASAAEgLDV_D_BwE)

The 2021 SalesGenie grocery sales data and dollar store data were used to visualize the distribution of the different types of stores and the sales volume information.

## Bizminer/Vertical IQ Percentages

Many of the functions used in the expense estimation component of the tool incorporate percentages taken from both Bizminer and Vertical IQ, two financial analysis and market research firms. The value of these percentages determine how much of the total estimated revenue will be spent on a given category of expense. The two percentages, each based on industry three-year averages, are averaged together for use in the calculations. Although the user has the freedom to choose their own percentage via sliders in the side panel, these Bizminer/Vertical IQ percentages are set as defaults.

## [Google Places Data](https://developers.google.com/maps/documentation/places/web-service/overview)

The Google Places API is being used to find nearby stores and convert addresses to GPS coordinates. These stores help to determine our market size ("buffer zone") and factor in the effect of competition on store profitability.

## [Google GeoCoding](https://developers.google.com/maps/documentation/geocoding/overview) 

The Google Geo Codding API converts the addresses into latitude-longitude points which is used in the mapping the market.

## [Tigris](https://www.rdocumentation.org/packages/tigris/versions/2.0.3)

Tigris is a package designed to help developers use Census Bureau TIGER/Line files. This is being used to find county and place info and is being used to determine which cities are in the market area.
