---
title: "Estimating Total Revenue"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Estimating Total Revenue}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The functions in this section of the package estimate the total revenue of a store using the average spending per capita and the number of shoppers in each category for each type of market.

## Average Per Capita Grocery Spend

The `Avg_Capita_Grocery_Spending()` function calculates the average per capita spending. This value serves as a baseline for how much each shopper will spend on average in a grocery store per year. The function takes 2022 total US grocery sales data from IBIS and divides it by the 2022 total US population from the US Census Bureau.

Since the population and grocery sales have taken 2022 data, the change due to inflation for the current year must be accounted. This is done by adjusting the average per capita grocery spend according to the state index and inflation. The functions `Adj_Capita_Grocery_Spend()` and `State_Adj_Capita_Grocery_Spend()` does this by using CPI (Consumer Price Index) and RPP (Rural Price Parities), respectively.

The **Consumer Price Index** (CPI) is a measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services. So, adjusting according to the CPI accounts for the inflation in the US.

**Regional price parities** (RPP) measure the differences in price levels across states and metropolitan areas for a given year and are expressed as a percentage of the overall national price level. Adjusting according to this measure gives that state's average per capita spending on groceries for that year.

## Total Spend by Category

Not all shoppers have the same priority for all stores, and it is important that we classify them according to their preference for the store. So the next component needed for estimating the revenue is the number of shoppers in each category for each type of market.

Shoppers are classified into 3 categories:

-   ***Primary Shoppers:*** The people doing most of the household grocery shopping in that store.

-   ***Secondary Shoppers:*** Regular visitors for smaller purchases but will often do their weekly shopping elsewhere.

-   ***Rare Shoppers:*** People who are very occasional shoppers(only when necessary).

Location and accessibility are key factors affecting the preference for a shop. Shoppers are classified into 3 different populations based on their location:

-   ***Metro*****:** The population of the city in which the store is planned to open

-   ***Town:*** Population of all the cities in the market

-   ***Rural:*** Total rural population of the market

The functions: `Primary_Shopper_Count()`, `Secondary_Shopper_Count()`, and `Rare_Shopper_Count()` calculates the number of shoppers in each category for each type of market. These functions use some default values for the percentage of each type of shopper in the different populations. For example, if we take the primary shoppers count, it calculates this number by multiplying the different percentages of primary shoppers in the different markets. The percentage of primary shoppers is highest in the metro populations because there is a higher probability of people living in the same city as the store having that store as their primary shopping place compared to others who have to travel to get to that store. The outputs of these functions are multiplied with the average grocery spend calculated from the `State_Adj_Capita_Grocery_Spend()`to get the total spend by each of these groups in the functions `Total_Spend_Primary_Shoppers()`, `Total_Spend_Secondary_Shoppers()`, and `Total_Spend_Rare_Shoppers()`.

For information on data update frequency and sources, check out this table:

+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+
| **Variable name**                        | **Frequency**                     | **Source**                    | **Link**                                      | **Notes**                                                       |
+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+
| Total US Grocery Sales                   | Optional                          | IBIS                          |                                               | Default base year is taken as 2022                              |
+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+
| Total US population                      | Optional                          | US Census Bureau              |                                               | Default base year is taken as 2022                              |
+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+
| Estimated cumulative price increase(CPI) | yearly update/ Half yearly update | US Bureau of Labor Statistics | <https://data.bls.gov/timeseries/CUUR0000SA0> | CPI in the current year - CPI in the base year                  |
|                                          |                                   |                               |                                               |                                                                 |
|                                          |                                   |                               |                                               | For now, defaulting as 7 for 2023                               |
+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+
| State Index                              | yearly update                     | BEA                           | <https://tinyurl.com/2wvca7vy>                | Should be inputted by the user according to the store location. |
+------------------------------------------+-----------------------------------+-------------------------------+-----------------------------------------------+-----------------------------------------------------------------+

## Total Revenue Estimate

Total revenue is estimated by summing the total spend by primary, secondary, and rare shoppers by the `Total_Estimate_Revenue()`.
