---
title: "Alex_Markdown"
author: "Alex"
date: "2023-06-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyUSDA)
library(tidycensus)
library(ggplot2)
library(tidyverse)
library(rgeos)
library(readxl)
library(tigris)
library(dplyr)
```

```{r}
Rural_Population(county_pop, towns_pop, pct_county) {
  #This function subtracts the sum of all the towns populations from the county and multiplies it
  #by the percent of the county that the area covers to find the # of rural people there are
  return((county_pop - towns_pop)*pct_county)
}

```



```{r}
#TODO: Add file path for usda atlas
#Opens each of the sheets and adds them to a variable

access <- read_xlsx(path = "../ProjectData/usda_table_atlas.xlsx", sheet="ACCESS")
stores <- read_xlsx(path = "../ProjectData/usda_table_atlas.xlsx", sheet="STORES")
assistance <- read_xlsx(path = "../ProjectData/usda_table_atlas.xlsx", sheet="ASSISTANCE")
insecurity <- read_xlsx(path = "../ProjectData/usda_table_atlas.xlsx", sheet="INSECURITY")


head(access)
```

```{r}
#Takes the state and county codes from the fips codes supplied from tigris and makes them a 5 character long FIPS code
#Needed to join with other tables
#Realized GEOID in county table was the fips code, changed the function I was using to get tigris data, so this is unneeded
#But I don't feel like changing the name of the GEOID column in my df, so this is staying
tig_fips <- counties() %>% mutate("FIPS" = sprintf("%s%s",STATEFP,COUNTYFP))
head(tig_fips)
```
```{r}
access_df <- left_join(access, tig_fips)
stores_df <- left_join(stores, tig_fips)
assistance_df <- left_join(assistance, tig_fips)
insecurity_df <- left_join(insecurity, tig_fips)
head(access_df)



```
```{r}
#needs geometry
access_df %>% ggplot(aes(fill = access_df$LACCESS_POP15)) + 
  labs(title = "Low Access Population") +
  geom_sf(mapping = access_df$geometry) +
  scale_fill_viridis_c(option = "E")  
```





