```{r, message=FALSE, warning=FALSE}
library(sf)
library(dplyr)
library(tigris)
library(tidyr)
library(stringr)
library(tidycensus)
library(oce)
library(geosphere)
library(googleway)
library(ggmap)
library(stringr)
library(cli)
library(DSPGGrocery)
```

```{r}
#source(file = "../R/Address_Parser.R")
#source(file = "../R/Quadrant_Area.R")
#source(file = "../R/UTM_Zoner.R")
#source(file = Quadrant_Calculator())
source(file = "Auto_Pct.R")
source(file = "Rural_Pop.R")
source(file = "Cities_Pop.R")
source(file = "Haversine_Calculator.R")
source(file = "Metro_Pop.R")
source(file = "Pop_Binder.R")
source(file = "County_Identifier.R")
source(file = "Get_Cities_In_County.R")

#Need to be fixed
df_census_call_test <- readRDS("../ProjectData/df_census_call_test.RDS")
df_geocode_test <- readRDS("../ProjectData/df_geocode_test.RDS")
df_grocery_only_test <- readRDS("../ProjectData/df_grocery_only_test.RDS")
```


```{r}
address <- "st, Lamoni, ia"
popbinder_list <- Pop_Binder(address = address)

city_population <- Cities_Pop(df_city_state = popbinder_list$df_city_pop, city_county_state = df_census_call_test)

metro_population <- Metro_Pop(address, df_city_pop = popbinder_list$df_city_pop)

rural_population <- Rural_Pop(popbinder_list$df_city_pop,
                               geo_county = popbinder_list$county_name,
                               df_geocode = df_geocode_test,
                               df_grocery_only = df_grocery_only_test)

```


```{r}
#' Calculates Market Size
#' 
#' @author Alex Cory
#' 
#' @description 
#' this function automatically calculates the market size for a given address value.
#' 
#' @details
#' this function calls DSPGGrocery::Pop_Binder, DSPGGrocery::Cities_Pop, DSPGGrocery::Metro_Pop
#' and DSPGGrocery::Rural_Pop.
#' 
#' @param address an address separated by commas containing street, city, and abbreviated state.
#' Example: "Main Street, Lamoni, IA"
#' 
#' @returns
#' returns a list of atomic vectors containing city_population, metro_population,
#' and rural_population.
#' 
#' @export

Calc_Market_Size_debug <- function(address, df_census_call, df_geocode, df_grocery_only) {
  browser()

  register_google(key = Sys.getenv("PLACES_KEY"))

  popbinder_list <- Pop_Binder(address = address)

  city_population <- Cities_Pop(df_city_state = popbinder_list$df_city_pop,
                                city_county_state = df_census_call)

  metro_population <- Metro_Pop(address, df_city_pop = popbinder_list$df_city_pop)

  rural_population <- Rural_Pop(geo_county = popbinder_list$county_name,
                                df_geocode = df_geocode,
                                df_grocery_only = df_grocery_only,
                                df_city_pop = popbinder_list$df_city_pop,
                                popbinder = popbinder_list)

  MarketSizelist <- list(city_population = city_population,
                         metro_population = metro_population,
                         rural_population =  rural_population)

  return(MarketSizelist)
}
```

```{r}
Calc_Market_Size_debug("St, Lamoni, IA", df_census_call = df_census_call_test, 
                       df_geocode = df_geocode_test,
                       df_grocery_only = df_grocery_only_test)
```

```{r}
test_address <- "Main St, Alma, WI"
test_address2 <- "St, Lamoni, IA"
state = Address_Parser(test_address)[3]

testList <- Create_Circle_Buffer(address = test_address2, 
                                 api_key = Sys.getenv("PLACES_KEY"), 
                                 keyword = "grocery")
list2env(testList, .GlobalEnv)
```

```{r}
Calc_Market_Size(address = test_address, 
                 df_census_call = df_census_call, 
                 df_geocode = df_geocode, 
                 df_grocery_only = df_grocery_only,
                 state =  state$state[1])
```

