
```{r}
library(dplyr)
library(oce)
```

```{r}
#This is the DF from the Google API call. Can be found in Harun/StoresOutputAPI.rmd
df_places_grocery
```

```{r}

#For each loop
#Compare the GPS coordinates to the origin to determine which direction it is to origin
#Compare new store to current nearest store in that direction
#How to handle diagonals?
#What if there are more or less than four closest stores
#Should this just use Voronoi


#Creates a new dataframe with the Lat, Long, and Name columns
#This step is completely unnecessary, but the original DF
#had awful column names and I didn't want to have to look at all 
#the other columns
api_stores <- data.frame( Name = df_places_grocery$name, 
                          Lat = df_places_grocery$geometry$location$lat,
                          Long = df_places_grocery$geometry$location$lng)

View(api_stores)


#I want to subtract each lat and long from the given lat and long
#the difference will tell me how far away in what direction each store is
#then I can use the min and max functions to figure out the closest store
#in each cardinal direction
#I also need to specifically look at only positive and only negative values
#Depending on which direction I'm looking in

#TODO: Error checking for in case there are no stores in one quadrant

df_geocode
UTM_df <- oce::lonlat2utm(longitude = api_stores$Long, 
                latitude = api_stores$Lat,
                zone = UTM_Zoner(abs(api_stores$Long[1])))
#This works, but we lose accuracy every 6 degrees of longitude. This is because we are just using the zone from the first store instead of using a different longitude for each store.
api_stores <- cbind(api_stores, UTM_df)





#Testing values 
df_geocode$lat <- 42.30791
df_geocode$lng <- -95.05114




UTM_geo <- oce::lonlat2utm(longitude = df_geocode$lng, 
                latitude = df_geocode$lat,
                zone = UTM_Zoner(abs(api_stores$Long[1])))
df_geocode <- cbind(df_geocode, UTM_geo)
print(df_geocode)
#This is adding the columns with the difference, but with Lake view Foods, 
#it only has one negative value

api_stores$Lat_Diff <- with(api_stores, as.numeric(api_stores$easting) -
                              as.numeric(df_geocode$easting))
api_stores$Long_Diff <- with(api_stores, as.numeric(api_stores$northing) - 
                               as.numeric(df_geocode$northing))
#Now that I have these points, I can figure out how far away each other point is
#using the Pythagorean theorem
api_stores



```
