```{r}
library(ggplot2)
library(dplyr)
library(DSPGGrocery)
library(tidycensus)
```


```{r}
GetPop <- function(fips) {
  #Broken
  pop <- get_decennial(fips)
  return(pop)
}
```
```{r}
GetArea <- function(fips) {
  area <- select(tig_fips$ALAND, where(tig_fips$FIPS == fips))
  
  
  
}
```


```{r}
percent_county_pop <- function(total_area, fips) {
  #Broken
 
   
  
}
```


# Main Function
Takes the input from user and computes the area of each quadrant.
```{r}

north_quad <- readline("Enter distance to closest Northern store (Miles): ")
east_quad <- readline("Enter distance to closest Eastern store (Miles): ")
south_quad <- readline("Enter distance to closest Southern store (Miles): ")
west_quad <- readline("Enter distance to closest Western store (Miles): ")

north_quad = as.numeric(north_quad)
east_quad = as.numeric(east_quad)
south_quad = as.numeric(south_quad)
west_quad = as.numeric(west_quad)


#THIS IS ONLY FOR TESTING
north_quad = 4
east_quad = 0
south_quad = 0
west_quad = 0

print(TotalArea(north_quad,east_quad,south_quad,west_quad))

```
