```{r}
library(ggplot2)
library(plotly)
library(readxl)
library(dplyr)
library(tidyverse)
```

# Pathing

```{r}
#'*File Directory*
path <- Sys.getenv("SalesGenie")
excel_file <- "salesgenie_dollar_stores.xlsx"
excel_file_1<-"salesgenie_all_grocery.xlsx"
excel_file_2<-"salesgenie_large_chain_grocery_stores.xlsx"
dollar_store_data <- read_excel(file.path(path, excel_file))
grocery_store_data<-read_excel(file.path(path,excel_file_1))
chain_grocery_store_data<-read_excel(file.path(path,excel_file_2))
```

```{r}
p <- ggplot(data = dollar_store_data, 
            aes(x = Company_Name, fill = Location_Sales_Volume_Range)) +
            geom_bar(position = "dodge")+
  ggtitle("Location Sales Volume distribution") +
  xlab("Dollar Store Chain Name") + ylab("Number of Stores")
ggplotly(p)
```

```{r}
p <- ggplot(data = dollar_store_data, aes(x = Company_Name, fill = Location_Sales_Volume_Range))+
  geom_bar()+
  ggtitle("Location Sales Volume distribution") +
  xlab("Dollar Store Chain Name") + ylab("Number of Stores")
ggplotly(p)%>% 
  layout(barmode = "stack")
```

```{r}
companyname_by_count <- ggplot(data = dollar_store_data, aes(x = Company_Name)) +
            geom_bar(position = "dodge")+
  ggtitle("Dollar Store Distribution by Store Name") +
  xlab("Store Name") + ylab("Number of Stores")
ggplotly(companyname_by_count)
```
```{r}
companyname_by_count_google <- ggplot(data = Google_Places_DollarStores, aes(x = name)) +
            geom_bar(position = "dodge")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("Dollar Store Distribution by Chain Name") +
  xlab("Chain Name") + ylab("Number of Stores")
ggplotly(companyname_by_count_google)
  
```


```{r}
num_dollar_stores<-dollar_store_data%>%
ggplot(aes(x = Mailing_City)) +
            geom_bar(position = "dodge")+

  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Dollar Store Distribution by Mailing City") +
  xlab("Mailing City") + ylab("Number of Stores")
ggplotly(num_dollar_stores)
```


```{r}

num_dollar_stores <- dollar_store_data %>%
  group_by(Mailing_City) %>%
  summarize(count = n()) %>%
  filter(count > 1) %>%
  ggplot(aes(x = reorder(Mailing_City,-count), y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Dollar Store Distribution by Mailing City") +
  xlab("Mailing City") + ylab("Number of Stores")

ggplotly(num_dollar_stores)
```


```{r}
sales_dollar <- dollar_store_data%>%
                      filter(Location_Sales_Volume_Range!="NA")%>%
                      ggplot(aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')),
                              fill = Company_Name)) +
  coord_flip()+
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for Dollar Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_dollar)
```


```{r}
chain_grocery_store_data$Company_Name <- str_replace_all(
  chain_grocery_store_data$Company_Name,
  c("Hv-Vee"= "Hy-Vee","A Hy-Vee Co"="Hy-Vee",
    "Hy-Vee Inc"="Hy-Vee","Hy-Vee Mainstreet"="Hy-Vee",
    "Fareway Grocery"="Fareway","Fareway Stores Inc-Meat Market"="Fareway",
    "Fresh Thyme Farmers Market"="Fareway"))
```

```{r}
g <- ggplot(data = chain_grocery_store_data, aes(x = Company_Name, fill = Location_Sales_Volume_Range)) +
            geom_bar(position = "dodge")+
  ggtitle("Location Sales Volume distribution for Chain Grocery Stores") +
  xlab("Grocery Store Chain Name") + ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(g)
```
#TODO: Arrange the x axis cateories in ascending order.

```{r}
sales_chain_grocery <- ggplot(data = chain_grocery_store_data, 
                              aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')),
                              fill = Company_Name)) +
  coord_flip()+
            geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_chain_grocery)
```

```{r}
sales_chain_grocery <- chain_grocery_store_data%>%
                      filter(Location_Sales_Volume_Range!="NA")%>%
                      ggplot(aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')),
                              fill = Company_Name)) +
  coord_flip()+
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_chain_grocery)
```


```{r}
sales_chain_grocery_dodge <- ggplot(data = chain_grocery_store_data, 
                                    aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), 
                                     fill = Company_Name)) +
  geom_bar(position = "dodge") +
  coord_flip()+
  ggtitle("Location Sales Volume distribution for Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_chain_grocery_dodge)
```


```{r}
num_grocery_stores <- grocery_store_data %>%
  group_by(Mailing_City) %>%
  summarize(count = n()) %>%
  filter(count > 2) %>%
  ggplot(aes(x = reorder(Mailing_City,-count), y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Grocery Store Distribution by Mailing City") +
  xlab("Mailing City") + ylab("Number of Stores")

ggplotly(num_grocery_stores)
```

```{r}
num_chain_grocery_stores <- chain_grocery_store_data %>%
  group_by(Mailing_City) %>%
  summarize(count = n()) %>%
  filter(count > 1) %>%
  ggplot(aes(x = reorder(Mailing_City,-count), y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Grocery Chain Store Distribution by Mailing City") +
  xlab("Mailing City") + ylab("Number of Stores")

ggplotly(num_chain_grocery_stores)
```

```{r}
non_chain_grocery_store_data<-anti_join(grocery_store_data, chain_grocery_store_data)
```
```{r}
num_chain_grocery_stores <- non_chain_grocery_store_data %>%
  group_by(Mailing_City) %>%
  summarize(count = n()) %>%
  filter(count > 1) %>%
  ggplot(aes(x = reorder(Mailing_City,-count), y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Non Chain Grocery Store Distribution by Mailing City") +
  xlab("Mailing City") + ylab("Number of Stores")

ggplotly(num_chain_grocery_stores)
```

```{r}
sales_non_chain_grocery <- non_chain_grocery_store_data%>%
                      filter(Location_Sales_Volume_Range!="NA")%>%
                      ggplot(aes((x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million'))))) +
  coord_flip()+
            geom_bar(position = "stack") +
  ggtitle("Location Sales Volume Distribution for Non Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_non_chain_grocery)
```



```{r}
library(readr)
cities <- read_csv("C:\\Users\\srika\\Documents\\GitHub\\Grocery\\ProjectData\\cities.csv")
colnames(cities)[1] <- "Mailing_City"
colnames(cities)[5]<-"County_Name"
```

```{r}
#RUCC
ruralurbancodes2013 <- read_excel("C:\\Users\\srika\\Documents\\GitHub\\Grocery\\ProjectData\\Rural-Urban Continuum Codes\\ruralurbancodes2013.xls")
ruralurbancodes2013_iowa<-ruralurbancodes2013[,-c(4,6)]%>%
                           filter(State=="IA")%>%
                           mutate(County_Name = trimws(str_remove_all(County_Name, "County")))
```



```{r}
df_non_chain_grocery_county<-merge(non_chain_grocery_store_data ,cities, by='Mailing_City')
df_non_chain_grocery_county_clean<-df_non_chain_grocery_county[,c(1,4,19,27)]
df_rucc_non_chain_grocery<-merge(ruralurbancodes2013_iowa,
                                 df_non_chain_grocery_county_clean,
                                 by="County_Name")
```

```{r}
df_chain_grocery_county<-merge(chain_grocery_store_data ,cities, by='Mailing_City')
df_chain_grocery_county_clean<-df_chain_grocery_county[,c(1,4,19,27)]
df_rucc_chain_grocery<-merge(ruralurbancodes2013_iowa,
                                 df_chain_grocery_county_clean,
                                 by="County_Name")
```

```{r}
df_dollar_county<-merge(dollar_store_data ,cities, by='Mailing_City')
df_dollar_county_clean<-df_dollar_county[,c(1,4,19,27)]
df_rucc_dollar_store<-merge(ruralurbancodes2013_iowa,
                                 df_dollar_county_clean,
                                 by="County_Name")
```


```{r}
sales_non_chain_grocery_RUCC <- df_rucc_non_chain_grocery%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                ggplot(aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), 
                                     fill = factor(RUCC_2013 ))) +
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for non Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_fill_discrete(name="RUCC",
                      breaks=c("Counties in metro areas of 250,000 to 1 million population", 
                               "Counties in metro areas of fewer than 250,000 population",
                               "Population of 20,000 or more, adjacent to a metro area",
                               "Population of 20,000 or more, not adjacent to a metro area",
                               "Population of 2,500 to 19,999, adjacent to a metro area",
                               "Population of 2,500 to 19,999, not adjacent to a metro area",
                               "Less than 2,500 population, adjacent to a metro area",
                               "Less than 2,500 urban population, not adjacent to a metro area"))
ggplotly(sales_non_chain_grocery_RUCC)
```

```{r}
sales_non_chain_grocery_RUCC <- df_rucc_non_chain_grocery%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                ggplot(aes(x =factor(RUCC_2013, 
                                     level=c(1,2,3,4,5,6,7,8,9)), 
                                     fill = Location_Sales_Volume_Range)) +
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for non Chain Grocery Stores") +
  xlab("RUCC Code") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(sales_non_chain_grocery_RUCC)
```

```{r}
city_group<-read_csv("C:\\Users\\srika\\Box\\DSPG 2023\\Projects\\FFED Grocery Store\\Resources\\CityGroupClassifications-geomaster\\geomaster.csv")
colnames(city_group)[2]<-"Mailing_City"
city_group<-city_group[,c(1,2,3,4,5)]
city_group$GrpCode <- str_replace(city_group$GrpCode, "PG8", "Rest_of_the_State")
city_group$GrpCode <- str_replace(city_group$GrpCode, "PG9", "Rest_of_the_State")
county<-c("PGCO1","PGCO2","PGCO3","PGCO4","PGCO5")
```
```{r}
city_group_chain_grocery<-merge(chain_grocery_store_data ,city_group, by='Mailing_City')
city_group_chain_grocery_clean<-city_group_chain_grocery[,c(1,4,19,25,26)]
city_group_all_grocery<-merge(grocery_store_data,city_group,by="Mailing_City")
city_group_all_grocery_clean<-city_group_all_grocery[,c(1,4,19,25,26)]
city_group_non_chain_grocery<-merge(non_chain_grocery_store_data,city_group,by="Mailing_City")
city_group_non_chain_grocery_clean<-city_group_non_chain_grocery[,c(1,4,19,25,26)]
city_group_dollar_store<-merge(dollar_store_data,city_group,by="Mailing_City")
city_group_dollar_store_clean<-city_group_dollar_store[,c(1,4,19,25,26)]
```


```{r}
city_group_chain_sales <- city_group_chain_grocery_clean%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                filter(!(GrpCode %in% county))%>%
                                ggplot(aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), 
                                     fill = factor(GrpCode ))) +
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(city_group_chain_sales)
```

```{r}
# Calculate the percentage for each group
city_group_non_chain_sales <- city_group_non_chain_grocery_clean %>%
  filter(Location_Sales_Volume_Range != "NA") %>%
  filter(!(GrpCode %in% county)) %>%
  group_by(Location_Sales_Volume_Range, GrpCode) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)

# Plot the percentage
ggplot(city_group_non_chain_sales, aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), y = Percentage, fill = factor(GrpCode))) +
  geom_bar(stat = "identity", position = "stack") +
  coord_flip()+
  ggtitle("Location Sales Volume distribution for Non Chain Grocery Stores") +
  xlab("Sales Volume Range") +
  ylab("Percentage of Stores") +
  theme(axis.text.x = element_text(hjust = 1))
ggplotly()
```

```{r}
# Calculate the percentage for each group
city_group_non_chain_sales <- city_group_non_chain_grocery_clean %>%
  filter(Location_Sales_Volume_Range != "NA") %>%
  filter(!(GrpCode %in% county)) %>%
  group_by(GrpCode,Location_Sales_Volume_Range) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)

# Plot the percentage
ggplot(city_group_non_chain_sales, aes(x = factor(GrpCode),y=Percentage,
                                      fill = factor(Location_Sales_Volume_Range,
                                      level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')))) +
  geom_bar(stat = "identity", position = "stack") +
  ggtitle("Location Sales Volume distribution for Non Chain Grocery Stores") +
  coord_flip()+
  xlab("City Group") +
  ylab("Percentage of Stores") +
  scale_fill_discrete(name = "Location Sales Volume")+
  theme(axis.text.x = element_text(hjust = 1))
ggplotly()
```


```{r}
# Calculate the percentage for each group
city_group_non_chain_sales <- city_group_non_chain_grocery_clean %>%
  filter(Location_Sales_Volume_Range != "NA") %>%
  filter(!(GrpCode %in% county)) %>%
  filter(!(GrpCode %in% c("PG1","PG2","PG3","PG4")))%>%
  group_by(Location_Sales_Volume_Range, GrpCode) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)

# Plot the percentage
ggplot(city_group_non_chain_sales, aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), y = Percentage, fill = factor(GrpCode))) +
  geom_bar(stat = "identity", position = "stack") +
  coord_flip()+
  ggtitle("Location Sales Volume distribution for Non Chain Grocery Stores") +
  xlab("Sales Volume Range") +
  ylab("Percentage of Stores") +
  theme(axis.text.x = element_text(hjust = 1))
ggplotly()
```
```{r}
# Calculate the percentage for each group
city_group_non_chain_sales <- city_group_non_chain_grocery_clean %>%
  filter(Location_Sales_Volume_Range != "NA") %>%
  filter(!(GrpCode %in% county)) %>%
  group_by(Location_Sales_Volume_Range, GrpCode) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)%>%
  filter(!(GrpCode %in% c("PG1","PG2","PG3","PG4")))

# Plot the percentage
ggplot(city_group_non_chain_sales, aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), y = Percentage, fill = factor(GrpCode))) +
  geom_bar(stat = "identity", position = "stack") +
  coord_flip()+
  ggtitle("Location Sales Volume distribution for Non Chain Grocery Stores") +
  xlab("Sales Volume Range") +
  ylab("Percentage of Stores") +
  theme(axis.text.x = element_text(hjust = 1))
ggplotly()
```



```{r}
city_group_non_chain_sales <- city_group_non_chain_grocery_clean%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                filter(!(GrpCode %in% county))%>%
                                ggplot(aes(x =factor(Location_Sales_Volume_Range, 
                                     level=c('Less Than $500,000',
                                      '$500,000-1 Million',
                                      '$1-2.5 Million',
                                      '$2.5-5 Million',
                                      '$5-10 Million',
                                      '$10-20 Million',
                                      '$20-50 Million',
                                      '$50-100 Million',
                                      '$100-500 Million')), 
                                     fill = factor(GrpCode ))) +
  geom_bar(position = "stack") +
  ggtitle("Location Sales Volume distribution for Non Chain Grocery Stores") +
  xlab("Sales Volume Range") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(city_group_non_chain_sales)
```


```{r}
#Something is wrong with this plot
city_group_chain_sales <- city_group_chain_grocery_clean%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                filter(!(GrpCode %in% county))%>%
                                ggplot(aes(x =GrpCode)) +
  geom_bar(position = "stack") +
  ggtitle("Number of chain grocery Stores in different classification groups") +
  xlab("City group Classification code") + 
  ylab("Number of Stores")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(city_group_chain_sales)
```

```{r}
city_group_all_sales <- city_group_all_grocery_clean%>%
                                filter(Location_Sales_Volume_Range!="NA")%>%
                                filter(!(GrpCode %in% county))%>%
                                ggplot(aes(x =GrpCode)) +
  geom_bar(position = "stack") +
  ggtitle("Number of Cities in different classification groups") +
  xlab("City group Classification code") + 
  ylab("Number of Cities")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(city_group_all_sales)
```

```{r}
city_group_chain_sales <- city_group_chain_grocery_clean%>%
                                ggplot(aes(x = GrpCode)) +
  geom_bar(position = "stack") +
  ggtitle("Number of chain grocery Stores in different classification groups") +
  xlab("City group Classification code") + 
  ylab("Number of Cities")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(city_group_chain_sales)
```



```{r}
#number of non chain grocery store by city
nonchaingrocery_count<-non_chain_grocery_store_data %>%
                        count(Mailing_City, sort=TRUE)
colnames(nonchaingrocery_count)[2]<-"NCG_count"
#number of chain grocery store by city
chaingrocery_count<-chain_grocery_store_data%>%
                    count(Mailing_City,sort=TRUE)
colnames(chaingrocery_count)[2]<-"CG_count"
#number of dollar store by city
dollarstore_count<-dollar_store_data%>%
                      count(Mailing_City,sort=TRUE)
colnames(dollarstore_count)[2]<-"DS_count"
#Merge all into one data frame and add population with city group data set
ncg_cg_counts<-merge(nonchaingrocery_count,chaingrocery_count,all=TRUE)
ncg_cg_ds_counts<-merge(ncg_cg_counts,dollarstore_count,all=TRUE)
ncg_cg_ds_counts[is.na(ncg_cg_ds_counts)] <- 0
storetype_grp_pop<-merge(ncg_cg_ds_counts,city_group,all=TRUE)
storetype_grp_pop[is.na(storetype_grp_pop)] <- 0
storetype_grp_pop$total_grocery<-storetype_grp_pop$NCG_count+storetype_grp_pop$CG_count
storetype_grp_pop$pop_store_ratio<-storetype_grp_pop$Pop20/storetype_grp_pop$total_grocery
```

```{r}
storetype_rucc_pop <-merge(cities,storetype_grp_pop,by="Mailing_City")
storetype_rucc_pop<-merge(storetype_rucc_pop,ruralurbancodes2013_iowa,by="County_Name")
storetype_rucc_pop$GrpCode <- str_replace(storetype_rucc_pop$GrpCode, "PG8", "Rest_of_the_State")
storetype_rucc_pop$GrpCode <- str_replace(storetype_rucc_pop$GrpCode, "PG9", "Rest_of_the_State")
storetype_rucc_pop<-storetype_rucc_pop[,-c(6,7,8,9,10,21,20)]


```


```{r}
#Cities with population store ratio more than 5000"
popratio<-storetype_grp_pop%>%
  filter(pop_store_ratio!=Inf)%>%
  filter(pop_store_ratio>5000)%>%
   filter(!(GrpCode %in% county))%>%
  ggplot(aes(x = reorder(Mailing_City,-pop_store_ratio), y =pop_store_ratio,fill=GrpCode)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Cities With population Grocery Store Ratio More Than 5000") +
  xlab("Mailing City") + 
  ylab("Population / Number Of Stores")
ggplotly(popratio)

```

```{r}
#This graph shows the cities in Iowa which has 1 grocery store for every 500 or less customers.
popratio<-storetype_grp_pop%>%
  filter(pop_store_ratio!=Inf)%>%
  filter(pop_store_ratio<1000)%>%
  filter(!(GrpCode %in% county))%>%
  ggplot(aes(x = reorder(Mailing_City,-pop_store_ratio), y =pop_store_ratio,fill=GrpCode)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Cities With Population Grocery Store Ratio Less Than 1000") +
  xlab("Mailing City") + 
  ylab("Population / Number Of Stores")
ggplotly(popratio)
```

```{r}
#This graph shows the cities in Iowa which has 1 grocery store for every 500 or less customers.
popratiobox<-storetype_grp_pop%>%
  filter(pop_store_ratio!=Inf)%>%
  filter(!(GrpCode %in% county))%>%
  ggplot(aes(x = reorder(GrpCode,-pop_store_ratio), y =pop_store_ratio,fill=GrpCode)) +
  geom_boxplot() +
  coord_flip()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Population Grocery Store Ratio By Group Code") +
  xlab("City Group") + 
  ylab("Population / Number Of Stores")
ggplotly(popratiobox)
```



```{r}
#Population by number of grocery stores
scatter_pop_num_grocery <-storetype_grp_pop%>%
  filter(total_grocery>0)%>%
  filter(!(GrpCode=="PG1"))%>%
  filter(!(GrpCode %in% county))%>%
  ggplot(aes(x = Pop20, y = total_grocery, color = factor(GrpCode))) +
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)

ggplotly(scatter_pop_num_grocery)
```


```{r}
rucc_pop_num_grocery <-storetype_rucc_pop%>%
  filter(total_grocery>0)%>%
  ggplot(aes(x = Pop20, y = total_grocery, color = factor(RUCC_2013))) +
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Number of grocery stores by population")
ggplotly(rucc_pop_num_grocery)
```

```{r}
ncg_ds_cg_plot <-storetype_rucc_pop%>%
  filter(total_grocery>3)%>%
  pivot_longer(cols =c(NCG_count,CG_count,DS_count),
                               names_to = "Store_Type",
                               values_to = "Count")

  ggplot(ncg_ds_cg_plot, aes(x = Mailing_City, y = Count, fill = Store_Type)) +
  geom_bar(position="dodge", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle("Distribution of diferrent type of stores By Mailing City") +
    labs(subtitle = "Chain,Non chain Grocery stores and Dollar Stores")+
    xlab("Mailing_City") + 
    ylab("Number_Of Stores")
  ggplotly()
```

```{r}
PG1 <- storetype_rucc_pop %>%
  filter(GrpCode == "PG1") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG1")
PG2<-storetype_rucc_pop %>%
  filter(GrpCode == "PG2") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG2")
PG3<-storetype_rucc_pop %>%
  filter(GrpCode == "PG3") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG3")
PG4<-storetype_rucc_pop %>%
  filter(GrpCode == "PG4") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG4")
PG5A<-storetype_rucc_pop %>%
  filter(GrpCode == "PG5A") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG5A")
PG5N<-storetype_rucc_pop %>%
  filter(GrpCode == "PG5N") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG5N")
PG6<-storetype_rucc_pop %>%
  filter(GrpCode == "PG6") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG6")
PG7<-storetype_rucc_pop %>%
  filter(GrpCode == "PG7") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PG7")
Rest_of_the_State<-storetype_rucc_pop %>%
  filter(GrpCode == "Rest_of_the_State") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="Rest_of_the_State")
PGCO1<-storetype_rucc_pop %>%
  filter(GrpCode == "PGCO1") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PGCO1")
PGCO2<-storetype_rucc_pop %>%
  filter(GrpCode == "PGCO2") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PGCO2")
PGCO3<-storetype_rucc_pop %>%
  filter(GrpCode == "PGCO3") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PGCO3")
PGCO4<-storetype_rucc_pop %>%
  filter(GrpCode == "PGCO4") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PGCO4")
PGCO5<-storetype_rucc_pop %>%
  filter(GrpCode == "PGCO5") %>%
  summarise(CG_count = sum(CG_count),NCG_count=sum(NCG_count),DS_count=sum(DS_count),GrpCode="PGCO5")
PGs<-rbind(PG1,PG2,PG3,PG4,PG5A,PG5N,PG6,PG7,Rest_of_the_State,PGCO1,PGCO2,PGCO3,PGCO4,PGCO5)
PGs_filtered<-PGs%>%
  filter(!(GrpCode %in% county))%>%
  mutate(sum=CG_count+NCG_count+DS_count)%>%
  mutate(grocery_alone=CG_count+NCG_count)%>%
  mutate(CG_total=100*CG_count/sum(CG_count),
         NCG_total=100*NCG_count/sum(NCG_count),
         DS_total=100*DS_count/sum(DS_count))

```


```{r}
PGs_plot <-PGs%>%
  filter(!(GrpCode %in% county))%>%
  pivot_longer(cols =c(NCG_count,CG_count,DS_count),
                               names_to = "Store_Type",
                               values_to = "Count")

  ggplot(PGs_plot, aes(x = GrpCode, y = Count, fill = Store_Type)) +
  geom_bar(position="dodge", stat="identity")+
    scale_x_discrete(labels=c("PG1" = "PG1: >=10,000 Core county of a MSA",
                              "PG2" = "PG2: >=10,000 Non-core MSA county",
                              "PG3" = "PG3: 2,500 to 9,999 Non-metro county",
                              "PG4"="PG4: 2,500 to 9,999 Metro county",
                              "PG5A"="500 to 2,499 Non-metro, 
                              adjacent to a MSA  ",
                              "PG5N"="500 to 2,499 Non-metro,
                              not adjacent to a MSA  ",
                              "PG6"="500 to 2,499 Metro county",
                              "PG7"="250 to 499 Any county",
                              "Rest_of_the_State"))+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle("Distribution Of Different Type Of Stores") +
    labs(subtitle = "By City Group Classification")+
    xlab("Group Code") + 
    ylab("Number Of Stores")
  ggplotly()
```

```{r}
PGs_plot_pct <-PGs_filtered%>%
  #Remove PGCOs
  filter(!(GrpCode %in% county))%>%
  #Pivot to plot by store type
  pivot_longer(cols =c(NCG_count,CG_count,DS_count),
                               names_to = "Store_Type",
                               values_to = "Count")
  #plot the percentage of each store type in a given city group. 
  #Percentage = 100*count of stores/sum of all the store
  ggplot(PGs_plot_pct, aes(x =GrpCode, y = 100*Count/sum, fill =Store_Type)) +
  geom_bar(position="stack", stat="identity")+
    #Flip coordinated to read the axis
    coord_flip()+
    #Rename to decribe access
    scale_x_discrete(labels=c("PG1" = ">=10,000 Core county of a MSA",
                              "PG2" = ">=10,000 Non-core MSA county",
                              "PG3" = "2,500 to 9,999 Non-metro county",
                              "PG4"="2,500 to 9,999 Metro county",
                              "PG5A"="500 to 2,499 Non-metro, 
                              adjacent to a MSA  ",
                              "PG5N"="500 to 2,499 Non-metro,
                              not adjacent to a MSA  ",
                              "PG6"="500 to 2,499 Metro county",
                              "PG7"="250 to 499 Any county",
                              "Rest_of_the_State"))+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle("Distribution Of Different Type Of Stores") +
    labs(subtitle = "By City Group Classification")+
    xlab("Group Classification") + 
    ylab("Percentage Of Stores")
  ggplotly()
```



```{r}
PGs_pct <-PGs_filtered%>%
  filter(!(GrpCode %in% county))%>%
  pivot_longer(cols =c(NCG_total,CG_total,DS_total),
                               names_to = "Store_Type",
                               values_to = "Count")

  ggplot(PGs_pct, aes(x = Store_Type, y = Count, fill =GrpCode)) +
  geom_bar(position="stack", stat="identity")+
    scale_x_discrete(labels=c("CG_total"="Chain_Grocery_Stores",
                              "NCG_total"="Non_Chain_Grocery_Stores",
                              "DS_total"="Dollar_Stores"))+
    coord_flip()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle("Distribution Of Different Type Of Stores") +
    labs(subtitle = "By City Group Classification")+
    xlab("Store Type") + 
    ylab("Percentage Of Stores")
  ggplotly()
```


```{r}

column_totals <- colSums(PGs[, sapply(PGs, is.numeric)])
total_row <- data.frame(t(column_totals))
total_row <- data.frame(Non_numeric_Column = "Total", total_row, stringsAsFactors = FALSE)
total_row$Non_numeric_Column==total_row$GrpCode
total_row<-total_row%>%
  rename(GrpCode = 1)
              
PGs_total<-rbind(PGs,total_row)
PGs_total
```

```{r}
write.csv(PGs_filtered,"C:\\Users\\srika\\Desktop\\PGs_filtered.csv")
write.csv(PGs,"C:\\Users\\srika\\Desktop\\PGs.csv")
write.csv(city_group_non_chain_grocery_clean,"C:\\Users\\srika\\Desktop\\city_group_non_chain_grocery_clean.csv")
write.csv(storetype_grp_pop,"C:\\Users\\srika\\Desktop\\storetype_grp_pop.csv")
write.csv(city_group_chain_grocery_clean,"C:\\Users\\srika\\Desktop\\city_group_chain_grocery_clean.csv")
write.csv(city_group_dollar_store_clean,"C:\\Users\\srika\\Desktop\\city_group_dollar_store_clean.csv")
```




